soo5717/2021-Algorithm-Study

Programmers/suyeon/dfs_bfs/네트워크.py, Programmers/suyeon/dfs_bfs/단어 변환.py, Programmers/suyeon/dfs_bfs/타겟 넘버.py
[Programmers-43163] 단어 변환
[Programmers-43162] 네트워크
[Programmers-43165] 타겟 넘버
=> [Programmers-dfs_bfs] suyeon

Programmers/suyeon/README.md, Programmers/suyeon/dfs_bfs/단어 변환.py, Programmers/suyeon/hash/베스트앨범.py, Programmers/suyeon/hash/위장.py, Programmers/suyeon/hash/전화번호 목록.py
[Programmers-42577] 전화번호 목록
[Programmers-42579] 베스트앨범
[Programmers-42578] 위장
[Programmers-43163] 단어 변환
=> [Programmers-hash] suyeon

Programmers/suyeon/README.md, Programmers/suyeon/sort/H-Index.py, Programmers/suyeon/sort/K번째수.py, Programmers/suyeon/sort/가장 큰 수.py
[Programmers-42747] H-Index
[Programmers-42748] K번째수
[Programmers-42746] 가장 큰 수
=> [Programmers-sort] suyeon

Programmers/suyeon/README.md, Programmers/suyeon/binary_search/입국심사.py, Programmers/suyeon/binary_search/징검다리.py
[Programmers-43236] 징검다리
[Programmers-43238] 입국심사
=> [Programmers-binary_search] suyeon

Programmers/suyeon/README.md, Programmers/suyeon/dynamic_programming/N으로 표현.py, Programmers/suyeon/dynamic_programming/등굣길.py, Programmers/suyeon/dynamic_programming/정수 삼각형.py
[Programmers-42895] N으로 표현
[Programmers-43105] 정수 삼각형
[Programmers-42898] 등굣길
=> [Programmers-dynamic_programming] suyeon

Programmers/suyeon/README.md, Programmers/suyeon/heap/더 맵게.py, Programmers/suyeon/heap/디스크 컨트롤러.py, Programmers/suyeon/heap/이중우선순위큐.py
[Programmers-42626] 더 맵게
[Programmers-42628] 이중우선순위큐
=> [Programmers-heap] suyeon

Programmers/suyeon/graph/가장 먼 노드.py, Programmers/suyeon/graph/방의 개수.py, Programmers/suyeon/graph/순위.py
[Programmers-49190] 방의 개수
[Programmers-49191] 순위
[Programmers-49189] 가장 먼 노드
=> [Programmers-graph] suyeon

Programmers/suyeon/2021_kakao_blind/메뉴 리뉴얼.py, Programmers/suyeon/2021_kakao_blind/순위 검색.py, Programmers/suyeon/2021_kakao_blind/신규 아이디 추천.py, Programmers/suyeon/README.md
[Programmers-72412] 순위 검색
[Programmers-72410] 신규 아이디 추천
[Programmers-72411] 메뉴 리뉴얼
=> [Programmers-2021_kakao_blind] suyeon

Programmers/suyeon/2020_kakao_blind/괄호 변환.py, Programmers/suyeon/2020_kakao_blind/문자열 압축.py, Programmers/suyeon/2020_kakao_blind/자물쇠와 열쇠.py
[Programmers-60057] 문자열 압축
[Programmers-60058] 괄호 변환
[Programmers-60059] 자물쇠와 열쇠
=> [Programmers-2020_kakao_blind] suyeon

Programmers/suyeon/2019_kakao_blind/실패율.py, Programmers/suyeon/2019_kakao_blind/오픈채팅방.py, Programmers/suyeon/2019_kakao_blind/후보키.py
[Programmers-42888] 오픈채팅방
[Programmers-42889] 실패율
[Programmers-42890] 후보키
=> [Programmers-2019_kakao_blind] suyeon

Programmers/suyeon/2018_kakao_blind/뉴스 클러스터링.py, Programmers/suyeon/2018_kakao_blind/캐시.py, Programmers/suyeon/2018_kakao_blind/프렌즈4블록.py
[Programmers-17680] 캐시
[Programmers-17677] 뉴스 클러스터링
[Programmers-17679] 프렌즈4블록
=> [Programmers-2018_kakao_blind] suyeon

Baekjoon/suyeon/17_week/최소 스패닝 트리.py, Baekjoon/suyeon/17_week/퇴사.py
[Baekjoon-1197] 최소 스패닝 트리
[Baekjoon-14501] 퇴사
=> [Baekjoon-17_week] suyeon

Baekjoon/suyeon/18_week/극장 좌석.py, Baekjoon/suyeon/18_week/행복 유치원.py
[Baekjoon-13164] 행복유치원
[Baekjoon-2302] 극장 좌석
=>  [Baekjoon-18_week] suyeon

Baekjoon/suyeon/19_week/지구 온난화.py
=> [Baekjoon-19_week] suyeon

Baekjoon/suyeon/20_week/2xn 타일링 2.py, Baekjoon/suyeon/20_week/LCS.py, Baekjoon/suyeon/20_week/소형기관차.py
[Baekjoon-11727] 2×n 타일링 2
[Baekjoon-9251] LCS
[Baekjoon-2616] 소형기관차
=> [Baekjoon-20_week] suyeon

Baekjoon/suyeon/21_week/철벽 보안 알고리즘.py, Baekjoon/suyeon/21_week/치킨 배달.py
[Baekjoon-15686] 치킨 배달
[Baekjoon-9322] 철벽 보안 알고리즘
=> [Baekjoon-21_week] suyeon

Baekjoon/suyeon/22_week/마법사 상어와 토네이도.py, Baekjoon/suyeon/22_week/빙고.py
=> [Baekjoon-22_week] suyeon

Baekjoon/suyeon/23_week/바이러스.py, Baekjoon/suyeon/23_week/연구소.py
[Baekjoon-2606] 바이러스
[Baekjoon-14502] 연구소
=> [Baekjoon-23_week] suyeon

Baekjoon/suyeon/25_week/단어 수학.py, Programmers/suyeon/25_week/거리두기 확인하기.py
=> [Baekjoon/Programmers-25_week] suyeon

Programmers/suyeon/26_week/수식 최대화.py
=> [Programmers-26_week] suyeon

Programmers/jiwoo/26_week/수식 최대화.py
거리두기 확인하기도 함수로 빼낸 부분 해보고 다시 푸시할게요!
=> [Programmers-26_week] jiwoo

Programmers/suyeon/27_week/튜플.py
=> [Programmers-27_week] suyeon

Programmers/eugene/27_week/튜플.py
=> [Programmers-27_week] eugene

Programmers/suyeon/28_week/파일명 정렬.py
=> [Programmers-28_week] suyeon

Programmers/eugene/34_week/방금 그곡.py
=> [Programmers-34_week] eugene
